### PR TITLE
SLG-0003: Error parameter implementation

### LINKED ISSUE #291: Adding Error to log functions
There was a slightly similar issue ([Simplify logging Error types #267](https://github.com/apple/swift-log/issues/267)) but I would like to give this another twist.

Basically all advanced logging systems accept a textual message and allow to add additional values to better describe the log event.
Any also many system allow to explicitly log an Error, not just as part of the message or metadata. Examples: Sentry, Datadog
These service do handle explicit errors in special ways like automated grouping, warning thresholds, incident management...
It's more complex to train these systems to analyze/filter/map the metadata of log events and perform the same routines as with explicit errors.

So I would like to propose to add an additional optional Error to the log functions that then can be send to log services.
Manual extraction of key values from an error, in it's simplest form `error.localizedDescription` or more complex, is not sufficient to leverage the potential of log services.

### Given
```swift
let error: Error? = ...
let logger = Logger(label: "com.example")
```

### Expected behavior
```swift
logger.error("message", error)
```
and a signature of the log(...) function of the LogHandler protocol
```swift
func log(
        level: Logging.Logger.Level,
        message: Logging.Logger.Message,
        error: Error?, // <<<<<<<<<< new line here
        metadata: Logging.Logger.Metadata?,
        source: String,
        file: String,
        function: String,
        line: UInt
    )
```

### Actual behavior
The given log functions `.log(...)` or explicit like `.error(...)` on a logger instance only accept a message and metadata where metadata is a String, or array/dictionary hierarchy where terminal elements are again String.

### SwiftLog version/commit hash
v1.5.4

### PR DESCRIPTION
**Pull request by samuelmurray**
Add new methods on `Logger` that allows the caller to attach `Error`s to log events, which will be propagated to the `LogHandler` as-is.

### Motivation:

Error information is typically of high interest in logs and log analysis. Currently, however, there is no standardized way of attaching `Error` information to logs, forcing users to either append it to the log message (`logger.warning("Something went wrong: \(error)")`), or attach it as metadata. By providing a separate parameter for this, and passing it as-is to the `LogHandler`, we both provide a standard, visible way to attach it, while also letting the `LogHandler` format it as it sees fit.
Closes #291 

### Modifications:

* New methods on `Logger` that accept an (optional) `Error`.
* An `error` property is added to `LogEvent`, which contains the `Error` from the new `Logger` methods.
* Adjust `LogHandler` implementations to serialize error as metadata.

### Result:

Users of `Logger` can use the new methods to attach `Error`s to their logs, which should help unify how `Error`s get logged in various code bases. 
`LogHandler` implementations can use the new `error` property on `LogEvent` and serialize it in a way that's suitable for that implementation. In general, extracting the string representation and the (qualified) type name should be a good baseline.

### CODE REVIEW

File: Sources/InMemoryLogging/InMemoryLogHandler.swift [hunk 1]
```diff
@@ -99,6 +99,11 @@ public struct InMemoryLogHandler: LogHandler {
         mergedMetadata = mergedMetadata.merging(self.metadata) { $1 }
         // ..merge in metadata from this log call, overwriting existing keys
         mergedMetadata = mergedMetadata.merging(event.metadata ?? [:]) { $1 }
+        // ..merge in error as metadata, overwriting existing keys
+        if let error = event.error {
+            mergedMetadata["error.message"] = "\(error)"
+            mergedMetadata["error.type"] = "\(String(describing: type(of: error)))"
+        }
```
Comment (samuelmurray) [inline Sources/InMemoryLogging/InMemoryLogHandler.swift]: Alternatively, we could add `error` as an attribute on `Entry`, but then we need to provide a custom implementation of `==`, e.g. where we compare the string representation and the type. Thoughts @kukushechkin ?

File: Tests/LoggingTests/TestLogger.swift [hunk 2]
```diff
@@ -295,22 +303,30 @@ extension History {
...
                 return false
             }
+            if let error {
+                guard case .string(let errorMessage) = entry.metadata?["error.message"], errorMessage == "\(error)" else {
+                    return false
+                }
+                guard case .string(let errorType) = entry.metadata?["error.type"], errorType == String(describing: type(of: error)) else {
+                    return false
+                }
+            }
```
Comment (samuelmurray) [inline Tests/LoggingTests/TestLogger.swift]: Alternatively, we could store the `error` as-is in `History`/`LogEntry`, and compare the string representation and type, that might be more sensible.

File: Sources/InMemoryLogging/InMemoryLogHandler.swift (hunk 1 above)
Comment (samuelmurray) [reply Sources/InMemoryLogging/InMemoryLogHandler.swift]: That might be better, since if people are using this handler for testing purposes, they probably want to access the raw error, rather than its string representation.

**Comment by samuelmurray** [comment]
Seeing as the change to `LogEvent` was released in [1.11.0](https://github.com/apple/swift-log/releases/tag/1.11.0), I opted to _not_ provide a default implementation where the error is serialized as metadata. As I mentioned in the review for that feature, I'm not sure how we could determine if a `LogHandler` supports this new attribute or not. So, the best we could do is to provide a fallback for those that still do not use `LogEvent` - but it would feel weird to provide a fallback for **old** versions (<=1.10.X) but not the most recent one (1.11.0).
As far as I understood the discourse in both these proposal reviews however, most people did not see this as a huge issue. But if you see some way to provide a fallback that works for 1.11.0, I'd be happy to add it.

File: Sources/InMemoryLogging/InMemoryLogHandler.swift (hunk 1 above)
Comment (kukushechkin) [reply Sources/InMemoryLogging/InMemoryLogHandler.swift]: I would add `error` to the `Entry`.

File: Sources/Logging/Logging.swift [hunk 3]
```diff
@@ -656,6 +882,7 @@ extension Logger {
     @inlinable
     public func critical(
         _ message: @autoclosure () -> Logger.Message,
+        error: (any Error)? = nil,
```
Comment (kukushechkin) [inline Sources/Logging/Logging.swift]: Hm, why didn't we make it `@autoclosure` in the proposal?

File: Sources/Logging/Logging.swift [hunk 4]
```diff
@@ -1745,6 +2003,11 @@ public struct StreamLogHandler: LogHandler {
             metadata.merge(explicit, uniquingKeysWith: { _, explicit in explicit })
         }
 
+        if let error {
```
Comment (kukushechkin) [inline Sources/Logging/Logging.swift:2127]: If there is no `explicit` metadata or a `provider`, error is dropped because of the early `nil` return.

File: Tests/LoggingTests/LoggingTest.swift [hunk 5]
```diff
@@ -623,7 +636,43 @@ struct LoggingTest {
...
+        testLogging.history.assertExist(level: .trace, message: "yes: trace", error: TestError.boom, source: "foo")
+        testLogging.history.assertExist(level: .debug, message: "yes: debug", error: TestError.boom, source: "foo")
+        testLogging.history.assertExist(level: .info, message: "yes: info", error: TestError.boom, source: "foo")
+        testLogging.history.assertExist(level: .notice, message: "yes: notice", error: TestError.boom, source: "foo")
+        testLogging.history.assertExist(level: .warning, message: "yes: warning", error: TestError.boom, source: "foo")
+        testLogging.history.assertExist(level: .error, message: "yes: error", error: TestError.boom, source: "foo")
+        testLogging.history.assertExist(level: .critical, message: "yes: critical", error: TestError.boom, source: "foo")
+    }
+
+    @Test func allLogLevelByFunctionRefWithoWithSourceWithoutError() {
```
Comment (kukushechkin) [inline Tests/LoggingTests/LoggingTest.swift]: A typo:

```suggestion
    @Test func allLogLevelByFunctionRefWithSourceWithoutError() {
```

File: Tests/LoggingTests/TestLogger.swift (hunk 2 above)
Comment (kukushechkin) [reply Tests/LoggingTests/TestLogger.swift]: I would suggest storing `error` as is.

File: Tests/InMemoryLoggingTests/InMemoryLogHandlerTests.swift [hunk 6]
```diff
@@ -69,6 +69,23 @@ struct InMemoryLogHandlerTests {
...
+        let (logHandler, logger) = self.makeTestLogger()
+        let error = TestError.boom
+        logger.info("hello", error: error)
+
+        #expect(
+            logHandler.entries == [
+                InMemoryLogHandler.Entry(
+                    level: .info,
+                    message: "hello",
+                    metadata: ["error.message": "\(error)", "error.type": "\(String(describing: type(of: error)))"]
```
Comment (kukushechkin) [inline Tests/InMemoryLoggingTests/InMemoryLogHandlerTests.swift]: If we store `error` as a property in the `Entry`, IMO, this would look more clean, just `error: error`.

File: Tests/LoggingTests/TestLogger.swift [hunk 7]
```diff
@@ -87,9 +87,15 @@ internal struct TestLogHandler: LogHandler {
             metadata.merge(explicitMetadata, uniquingKeysWith: { _, explicit in explicit })
         }
 
+        if let error = event.error {
```
Comment (kukushechkin) [inline Tests/LoggingTests/TestLogger.swift]: Is this expected error is now run two places: explicit `error` and the `metadata`?

**Review by kukushechkin — CHANGES_REQUESTED** [review]
Thank you for the implementation, looks great overall! Let's iron out magic `metadata` entries vs explict `error`.

**Comment by kukushechkin** [comment]
As for the failing CI checks:

- The API breakage check failing on a `package` method is annoying, but ok. 
- Benchmarks producing slightly different values is probably due to the infra changes, let's observe on the subsequent runs.
- Tests — in the proposal we have `String(reflecting:)` instead of `String(describing:)`, is there a reason to use `describing:`?
- And the formatting, but that one is self-explanatory.

File: Tests/LoggingTests/TestLogger.swift (hunk 2 above)
Comment (samuelmurray) [reply Tests/LoggingTests/TestLogger.swift]: Fixed

File: Sources/InMemoryLogging/InMemoryLogHandler.swift (hunk 1 above)
Comment (samuelmurray) [reply Sources/InMemoryLogging/InMemoryLogHandler.swift]: Fixed

File: Tests/LoggingTests/TestLogger.swift (hunk 7 above)
Comment (samuelmurray) [reply Tests/LoggingTests/TestLogger.swift]: Changed to storing raw errors in TestLogger

File: Sources/Logging/Logging.swift (hunk 4 above)
Comment (samuelmurray) [reply Sources/Logging/Logging.swift:2127]: Good catch, how about just adding that as a third check in the guard?

File: Tests/InMemoryLoggingTests/InMemoryLogHandlerTests.swift (hunk 6 above)
Comment (samuelmurray) [reply Tests/InMemoryLoggingTests/InMemoryLogHandlerTests.swift]: Fixed

File: Sources/Logging/Logging.swift (hunk 3 above)
Comment (samuelmurray) [reply Sources/Logging/Logging.swift]: Do you see a use case for this, or more to be consistent with `message` and `metadata`? 
The main motivation in the proposal is `try {...} catch { logger.warning(...) }`. In what cases would we have a computed error?

**Comment by samuelmurray** [comment]
> As for the failing CI checks:
> 
> * The API breakage check failing on a `package` method is annoying, but ok.
> * Benchmarks producing slightly different values is probably due to the infra changes, let's observe on the subsequent runs.
> * Tests — in the proposal we have `String(reflecting:)` instead of `String(describing:)`, is there a reason to use `describing:`?
> * And the formatting, but that one is self-explanatory.

Right, the `reflecting` vs `describing` was a mistake on my part, changed the tests and `InMemoryLogHandler` to use `reflecting` and added a test verifies that that we compare fully qualified names in the equality check.

**Comment by samuelmurray** [comment]
Unrelated to this PR:
Some files in this repo are getting quite long, especially `Logging.swift`. How about splitting it up some? For example, we could extract the included `LogHandler` implementations to separate files (similar to [providers in `swift-configuration`](https://github.com/apple/swift-configuration/tree/main/Sources/Configuration/Providers)), and maybe separate all the log methods to `Logging+methods.swift`.

File: Sources/InMemoryLogging/InMemoryLogHandler.swift [hunk 8]
```diff
@@ -99,8 +132,9 @@ public struct InMemoryLogHandler: LogHandler {
         mergedMetadata = mergedMetadata.merging(self.metadata) { $1 }
         // ..merge in metadata from this log call, overwriting existing keys
         mergedMetadata = mergedMetadata.merging(event.metadata ?? [:]) { $1 }
+        // ..merge in error as metadata, overwriting existing keys
```
Comment (kukushechkin) [inline Sources/InMemoryLogging/InMemoryLogHandler.swift]: Leftover comment.

```suggestion
```

File: Sources/Logging/Logging.swift (hunk 3 above)
Comment (kukushechkin) [reply Sources/Logging/Logging.swift]: Consistency and avoid unnecessary evaluation for a rare computed (if someone actually decides to have this) case.

File: Sources/Logging/Logging.swift (hunk 4 above)
Comment (kukushechkin) [reply Sources/Logging/Logging.swift:2127]: Yeah, looks reasonable.

File: Sources/Logging/Logging.swift (hunk 3 above)
Comment (samuelmurray) [reply Sources/Logging/Logging.swift]: Sure, I don't see why not!

**Comment by kukushechkin** [comment]
I've pushed an update to the benchmark thresholds, this should make it pass.

**Review by kukushechkin — APPROVED** [review]

File: Tests/LoggingTests/TestLogger.swift
Comment (FranzBusch) [inline Tests/LoggingTests/TestLogger.swift:1]: We should probably get rid of this `TestLogger` and replace it with the `InMemoryLogHandler` at some point in the future

**Review by FranzBusch — APPROVED** [review]

File: Tests/LoggingTests/TestLogger.swift (hunk 2 above)
Comment (gigadj111-cmd) [reply Tests/LoggingTests/TestLogger.swift]: https://github.com/vapor/console-kit.git

Comment (gigadj111-cmd) [reply Tests/LoggingTests/TestLogger.swift]: [](url)# Basic writing and formatting syntax

Create sophisticated formatting for your prose and code on GitHub with simple syntax.

## Headings

To create a heading, add one to six <kbd>#</kbd> symbols before your heading text. The number of <kbd>#</kbd> you use will determine the hierarchy level and typeface size of the heading.

```markdown
# A first-level heading
## A second-level heading
### A third-level heading
```

Screenshot of rendered GitHub Markdown showing sample h1, h2, and h3 headers, which descend in type size and visual weight to show hierarchy level.

When you use two or more headings, GitHub automatically generates a table of contents that you can access by clicking the "Outline" menu icon <svg version="1.1" width="16" height="16" viewBox="0 0 16 16" class="octicon octicon-list-unordered" aria-label="Table of Contents" role="img"><path d="M5.75 2.5h8.5a.75.75 0 0 1 0 1.5h-8.5a.75.75 0 0 1 0-1.5Zm0 5h8.5a.75.75 0 0 1 0 1.5h-8.5a.75.75 0 0 1 0-1.5Zm0 5h8.5a.75.75 0 0 1 0 1.5h-8.5a.75.75 0 0 1 0-1.5ZM2 14a1 1 0 1 1 0-2 1 1 0 0 1 0 2Zm1-6a1 1 0 1 1-2 0 1 1 0 0 1 2 0ZM2 4a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z"></path></svg> within the file header. Each heading title is listed in the table of contents and you can click a title to navigate to the selected section.

Screenshot of a README file with the drop-down menu for the table of contents exposed. The table of contents icon is outlined in dark orange.

## Styling text

You can indicate emphasis with bold, italic, strikethrough, subscript, or superscript text in comment fields and `.md` files.

| Style                  | Syntax              | Keyboard shortcut                                                                     | Example                                  | Output                                 |                                                   |
| ---------------------- | ------------------- | ------------------------------------------------------------------------------------- | ---------------------------------------- | -------------------------------------- | ------------------------------------------------- |
| Bold                   | `** **` or `__ __`  | <kbd>Command</kbd>+<kbd>B</kbd> (Mac) or <kbd>Ctrl</kbd>+<kbd>B</kbd> (Windows/Linux) | `**This is bold text**`                  | **This is bold text**                  |                                                   |
| Italic                 | `* *` or `_ _`      | <kbd>Command</kbd>+<kbd>I</kbd> (Mac) or <kbd>Ctrl</kbd>+<kbd>I</kbd> (Windows/Linux) | `_This text is italicized_`              | *This text is italicized*              |                                                   |
| Strikethrough          | `~~ ~~` or `~ ~`    | None                                                                                  | `~~This was mistaken text~~`             | ~~This was mistaken text~~             |                                                   |
| Bold and nested italic | `** **` and `_ _`   | None                                                                                  | `**This text is _extremely_ important**` | **This text is *extremely* important** |                                                   |
| All bold and italic    | `*** ***`           | None                                                                                  | `***All this text is important***`       | ***All this text is important***       |  |
| Subscript              | `<sub> </sub>`      | None                                                                                  | `This is a <sub>subscript</sub> text`    | This is a <sub>subscript</sub> text    |                                                   |
| Superscript            | `<sup> </sup>`      | None                                                                                  | `This is a <sup>superscript</sup> text`  | This is a <sup>superscript</sup> text  |                                                   |
| Underline              | `<ins> </ins>`      | None                                                                                  | `This is an <ins>underlined</ins> text`  | This is an <ins>underlined</ins> text  |                                                   |

## Quoting text

You can quote text with a <kbd>></kbd>.

```markdown
Text that is not a quote

> Text that is a quote
```

Quoted text is indented with a vertical line on the left and displayed using gray type.

Screenshot of rendered GitHub Markdown showing the difference between normal and quoted text.

> \[!NOTE]
> When viewing a conversation, you can automatically quote text in a comment by highlighting the text, then typing <kbd>R</kbd>. You can quote an entire comment by clicking <svg version="1.1" width="16" height="16" viewBox="0 0 16 16" class="octicon octicon-kebab-horizontal" aria-label="The horizontal kebab icon" role="img"><path d="M8 9a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3ZM1.5 9a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3Zm13 0a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3Z"></path></svg>, then **Quote reply**. For more information about keyboard shortcuts, see [Keyboard shortcuts](/en/get-started/accessibility/keyboard-shortcuts).

## Quoting code

You can call out code or a command within a sentence with single backticks. The text within the backticks will not be formatted. You can also press the <kbd>Command</kbd>+<kbd>E</kbd> (Mac) or <kbd>Ctrl</kbd>+<kbd>E</kbd> (Windows/Linux) keyboard shortcut to insert the backticks for a code block within a line of Markdown.

```markdown
Use `git status` to list all new or modified files that haven't yet been committed.
```

Screenshot of rendered GitHub Markdown showing that characters surrounded by backticks are shown in a fixed-width typeface, highlighted in light gray.

To format code or text into its own distinct block, use triple backticks.

````markdown
Some basic Git commands are:
```
git status
git add
git commit
```
````

Screenshot of rendered GitHub Markdown showing a simple code block without syntax highlighting.

For more information, see [Creating and highlighting code blocks](/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).

If you are frequently editing code snippets and tables, you may benefit from enabling a fixed-width font in all comment fields on GitHub. For more information, see [About writing and formatting on GitHub](/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/about-writing-and-formatting-on-github#enabling-fixed-width-fonts-in-the-editor).

## Supported color models

In issues, pull requests, and discussions, you can call out colors within a sentence by using backticks. A supported color model within backticks will display a visualization of the color.

```markdown
The background color is `#ffffff` for light mode and `#000000` for dark mode.
```

Screenshot of rendered GitHub Markdown showing how HEX values within backticks create small circles of color, here white and then black.

Here are the currently supported color models.

| Color | Syntax                      | Example                             | Output                                                                                                                                                                         |
| ----- | --------------------------- | ----------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| HEX   | <code>\`#RRGGBB\`</code>    | <code>\`#0969DA\`</code>            | Screenshot of rendered GitHub Markdown showing how HEX value #0969DA appears with a blue circle.       |
| RGB   | <code>\`rgb(R,G,B)\`</code> | <code>\`rgb(9, 105, 218)\`</code>   | Screenshot of rendered GitHub Markdown showing how RGB value 9, 105, 218 appears with a blue circle.   |
| HSL   | <code>\`hsl(H,S,L)\`</code> | <code>\`hsl(212, 92%, 45%)\`</code> | Screenshot of rendered GitHub Markdown showing how HSL value 212, 92%, 45% appears with a blue circle. |

> \[!NOTE]
>
> * A supported color model cannot have any leading or trailing spaces within the backticks.
> * The visualization of the color is only supported in issues, pull requests, and discussions.

## Links

You can create an inline link by wrapping link text in brackets `[ ]`, and then wrapping the URL in parentheses `( )`. You can also use the keyboard shortcut <kbd>Command</kbd>+<kbd>K</kbd> to create a link. When you have text selected, you can paste a URL from your clipboard to automatically create a link from the selection.

You can also create a Markdown hyperlink by highlighting the text and using the keyboard shortcut <kbd>Command</kbd>+<kbd>V</kbd>. If you'd like to replace the text with the link, use the keyboard shortcut <kbd>Command</kbd>+<kbd>Shift</kbd>+<kbd>V</kbd>.

`This site was built using [GitHub Pages](https://pages.github.com/).`

Screenshot of rendered GitHub Markdown showing how text within brackets, "GitHub Pages," appears as a blue hyperlink.

> \[!NOTE]
> GitHub automatically creates links when valid URLs are written in a comment. For more information, see [Autolinked references and URLs](/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls).

## Section links

You can link directly to any section that has a heading. To view the automatically generated anchor in a rendered file, hover over the section heading to expose the <svg version="1.1" width="16" height="16" viewBox="0 0 16 16" class="octicon octicon-link" aria-label="the link" role="img"><path d="m7.775 3.275 1.25-1.25a3.5 3.5 0 1 1 4.95 4.95l-2.5 2.5a3.5 3.5 0 0 1-4.95 0 .751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018 1.998 1.998 0 0 0 2.83 0l2.5-2.5a2.002 2.002 0 0 0-2.83-2.83l-1.25 1.25a.751.751 0 0 1-1.042-.018.751.751 0 0 1-.018-1.042Zm-4.69 9.64a1.998 1.998 0 0 0 2.83 0l1.25-1.25a.751.751 0 0 1 1.042.018.751.751 0 0 1 .018 1.042l-1.25 1.25a3.5 3.5 0 1 1-4.95-4.95l2.5-2.5a3.5 3.5 0 0 1 4.95 0 .751.751 0 0 1-.018 1.042.751.751 0 0 1-1.042.018 1.998 1.998 0 0 0-2.83 0l-2.5 2.5a1.998 1.998 0 0 0 0 2.83Z"></path></svg> icon and click the icon to display the anchor in your browser.

Screenshot of a README for a repository. To the left of a section heading, a link icon is outlined in dark orange.

If you need to determine the anchor for a heading in a file you are editing, you can use the following basic rules:

* Letters are converted to lower-case.
* Spaces are replaced by hyphens (`-`). Any other whitespace or punctuation characters are removed.
* Leading and trailing whitespace are removed.
* Markup formatting is removed, leaving only the contents (for example, `_italics_` becomes `italics`).
* If the automatically generated anchor for a heading is identical to an earlier anchor in the same document, a unique identifier is generated by appending a hyphen and an auto-incrementing integer.

For more detailed information on the requirements of URI fragments, see [RFC 3986: Uniform Resource Identifier (URI): Generic Syntax, Section 3.5](https://www.rfc-editor.org/rfc/rfc3986#section-3.5).

The code block below demonstrates the basic rules used to generate anchors from headings in rendered content.

```markdown
# Example headings

## Sample Section

## This'll be a _Helpful_ Section About the Greek Letter Θ!
A heading containing characters not allowed in fragments, UTF-8 characters, two consecutive spaces between the first and second words, and formatting.

## This heading is not unique in the file

TEXT 1

## This heading is not unique in the file

TEXT 2

# Links to the example headings above

Link to the sample section: [Link Text](#sample-section).

Link to the helpful section: [Link Text](#thisll-be-a-helpful-section-about-the-greek-letter-Θ).

Link to the first non-unique section: [Link Text](#this-heading-is-not-unique-in-the-file).

Link to the second non-unique section: [Link Text](#this-heading-is-not-unique-in-the-file-1).
```

> \[!NOTE]
> If you edit a heading, or if you change the order of headings with "identical" anchors, you will also need to update any links to those headings as the anchors will change.

## Relative links

You can define relative links and image paths in your rendered files to help readers navigate to other files in your repository.

A relative link is a link that is relative to the current file. For example, if you have a README file in root of your repository, and you have another file in *docs/CONTRIBUTING.md*, the relative link to *CONTRIBUTING.md* in your README might look like this:

```text
[Contribution guidelines for this project](docs/CONTRIBUTING.md)
```

GitHub will automatically transform your relative link or image path based on whatever branch you're currently on, so that the link or path always works. The path of the link will be relative to the current file. Links starting with `/` will be relative to the repository root. You can use all relative link operands, such as `./` and `../`.

Your link text should be on a single line. The example below will not work.

```markdown
[Contribution
guidelines for this project](docs/CONTRIBUTING.md)
```

Relative links are easier for users who clone your repository. Absolute links may not work in clones of your repository - we recommend using relative links to refer to other files within your repository.

## Custom anchors

You can use standard HTML anchor tags (`<a name="unique-anchor-name"></a>`) to create navigation anchor points for any location in the document. To avoid ambiguous references, use a unique naming scheme for anchor tags, such as adding a prefix to the `name` attribute value.

> \[!NOTE]
> Custom anchors will not be included in the document outline/Table of Contents.

You can link to a custom anchor using the value of the `name` attribute you gave the anchor. The syntax is exactly the same as when you link to an anchor that is automatically generated for a heading.

For example:

```markdown
# Section Heading

Some body text of this section.

<a name="my-custom-anchor-point"></a>
Some text I want to provide a direct link to, but which doesn't have its own heading.

(… more content…)

[A link to that custom anchor](#my-custom-anchor-point)
```

> \[!TIP]
> Custom anchors are not considered by the automatic naming and numbering behavior of automatic heading links.

## Line breaks

If you're writing in issues, pull requests, or discussions in a repository, GitHub will render a line break automatically:

```markdown
This example
Will span two lines
```

However, if you are writing in an .md file, the example above would render on one line without a line break. To create a line break in an .md file, you will need to include one of the following:

* Include two spaces at the end of the first line.
  <pre>
  This example&nbsp;&nbsp;
  Will span two lines
  </pre>

* Include a backslash at the end of the first line.

  ```markdown
  This example\
  Will span two lines
  ```

* Include an HTML single line break tag at the end of the first line.

  ```markdown
  This example<br/>
  Will span two lines
  ```

If you leave a blank line between two lines, both .md files and Markdown in issues, pull requests, and discussions will render the two lines separated by the blank line:

```markdown
This example

Will have a blank line separating both lines
```

## Images

You can display an image by adding <kbd>!</kbd> and wrapping the alt text in `[ ]`. Alt text is a short text equivalent of the information in the image. Then, wrap the link for the image in parentheses `()`.

`Screenshot of a comment on a GitHub issue showing an image, added in the Markdown, of an Octocat smiling and raising a tentacle.`

Screenshot of a comment on a GitHub issue showing an image, added in the Markdown, of an Octocat smiling and raising a tentacle.

GitHub supports embedding images into your issues, pull requests, discussions, comments and `.md` files. You can display an image from your repository, add a link to an online image, or upload an image. For more information, see [Uploading assets](#uploading-assets).

> \[!NOTE]
> When you want to display an image that is in your repository, use relative links instead of absolute links.

Here are some examples for using relative links to display an image.

| Context                                                     | Relative Link                                                          |
| ----------------------------------------------------------- | ---------------------------------------------------------------------- |
| In a `.md` file on the same branch                          | `/assets/images/electrocat.png`                                        |
| In a `.md` file on another branch                           | `/../main/assets/images/electrocat.png`                                |
| In issues, pull requests and comments of the repository     | `../blob/main/assets/images/electrocat.png?raw=true`                   |
| In a `.md` file in another repository                       | `/../../../../github/docs/blob/main/assets/images/electrocat.png`      |
| In issues, pull requests and comments of another repository | `../../../github/docs/blob/main/assets/images/electrocat.png?raw=true` |

> \[!NOTE]
> The last two relative links in the table above will work for images in a private repository only if the viewer has at least read access to the private repository that contains these images.

For more information, see [Relative Links](#relative-links).

### The Picture element

The `<picture>` HTML element is supported.

## Lists

You can make an unordered list by preceding one or more lines of text with <kbd>-</kbd>, <kbd>\*</kbd>, or <kbd>+</kbd>.

```markdown
- George Washington
* John Adams
+ Thomas Jefferson
```

Screenshot of rendered GitHub Markdown showing a bulleted list of the names of the first three American presidents.

To order your list, precede each line with a number.

```markdown
1. James Madison
2. James Monroe
3. John Quincy Adams
```

Screenshot of rendered GitHub Markdown showing a numbered list of the names of the fourth, fifth, and sixth American presidents.

### Nested Lists

You can create a nested list by indenting one or more list items below another item.

To create a nested list using the web editor on GitHub or a text editor that uses a monospaced font, like [Visual Studio Code](https://code.visualstudio.com/), you can align your list visually. Type space characters in front of your nested list item until the list marker character (<kbd>-</kbd> or <kbd>\*</kbd>) lies directly below the first character of the text in the item above it.

```markdown
1. First list item
   - First nested list item
     - Second nested list item
```

> \[!NOTE]
> In the web-based editor, you can indent or dedent one or more lines of text by first highlighting the desired lines and then using <kbd>Tab</kbd> or <kbd>Shift</kbd>+<kbd>Tab</
